#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2014--, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qtp_sequencing import plugin


@click.command()
@click.option('--env-script', prompt='Environment script',
              default='conda activate qtp-sequencing')
@click.option('--ca-cert', prompt='Server certificate', default='None')
def config(env_script, ca_cert):
    """Generates the Qiita configuration files"""
    if ca_cert == 'None':
        ca_cert = None
    plugin.generate_config(env_script, 'start_qtp_sequencing',
                           ca_cert)


if __name__ == '__main__':
    config()
